name: "SmokeTest"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nasl-lint:
    name: Smoketest openvas-nasl-lint
    runs-on: ubuntu-latest
    container: ${{ github.repository }}-build:unstable
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v3
      - name: build
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Run Smoketest linter
        run: |
          make build
          ./run --openvasDir ../build/nasl/ --testFiles data
        working-directory: smoketest_lint
